<?xml version="1.0" encoding="utf-8"?><Database Name="ChatsDB" Class="ChatDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=ChatsDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ChatsDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblChatHistory" Member="tblChatHistories">
    <Type Name="tblChatHistory">
      <Column Name="ChatID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChatUserName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Chat" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DateSent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>