#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatSite
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ChatsDB")]
	public partial class ChatDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblChatHistory(tblChatHistory instance);
    partial void UpdatetblChatHistory(tblChatHistory instance);
    partial void DeletetblChatHistory(tblChatHistory instance);
    #endregion
		
		public ChatDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ChatsDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ChatDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblChatHistory> tblChatHistories
		{
			get
			{
				return this.GetTable<tblChatHistory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChatHistory")]
	public partial class tblChatHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ChatID;
		
		private string _ChatUserName;
		
		private string _Chat;
		
		private System.Nullable<System.DateTime> _DateSent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnChatIDChanging(int value);
    partial void OnChatIDChanged();
    partial void OnChatUserNameChanging(string value);
    partial void OnChatUserNameChanged();
    partial void OnChatChanging(string value);
    partial void OnChatChanged();
    partial void OnDateSentChanging(System.Nullable<System.DateTime> value);
    partial void OnDateSentChanged();
    #endregion
		
		public tblChatHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChatID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ChatID
		{
			get
			{
				return this._ChatID;
			}
			set
			{
				if ((this._ChatID != value))
				{
					this.OnChatIDChanging(value);
					this.SendPropertyChanging();
					this._ChatID = value;
					this.SendPropertyChanged("ChatID");
					this.OnChatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChatUserName", DbType="VarChar(500)")]
		public string ChatUserName
		{
			get
			{
				return this._ChatUserName;
			}
			set
			{
				if ((this._ChatUserName != value))
				{
					this.OnChatUserNameChanging(value);
					this.SendPropertyChanging();
					this._ChatUserName = value;
					this.SendPropertyChanged("ChatUserName");
					this.OnChatUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chat", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Chat
		{
			get
			{
				return this._Chat;
			}
			set
			{
				if ((this._Chat != value))
				{
					this.OnChatChanging(value);
					this.SendPropertyChanging();
					this._Chat = value;
					this.SendPropertyChanged("Chat");
					this.OnChatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateSent", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateSent
		{
			get
			{
				return this._DateSent;
			}
			set
			{
				if ((this._DateSent != value))
				{
					this.OnDateSentChanging(value);
					this.SendPropertyChanging();
					this._DateSent = value;
					this.SendPropertyChanged("DateSent");
					this.OnDateSentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
